version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name saiapp --s3-location s3://sai-s33/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src